service: desafio-bgc-brasil

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET
          cors: true

  getProductData:
    handler: handler.getProductData
    events:
      - http:
          path: /product-data
          method: GET
          cors: true