service: desafio-bgc-brasil

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET
          cors: true
